[package]
name = "blobary-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Blobary command-line interface (CLI)"
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = ["base58", "encrypt", "gzip", "lz4", "magic", "redis", "s3", "sqlite", "tar", "tracing"]
7z = ["dep:sevenz-rust"]
base58 = ["dep:bs58"]
dmg = [] # TODO: apple-dmg?
encrypt = ["blobary/encrypt"]
gzip = ["blobary/gzip"]
lz4 = ["blobary/lz4"]
magic = ["blobary/magic"]
redis = ["blobary/redis"]
s3 = ["blobary/s3"]
sqlite = ["blobary/sqlite"]
tar = ["dep:tar"]
tracing = ["blobary/tracing"]
zip = ["dep:zip"]

[dependencies]
#arrayvec = { version = "0.7.4", features = ["zeroize"] }
argfile = "0.1.6"
bs58 = { version = "0.5.0", optional = true }
blobary.workspace = true
clap = { version = "4.4.6", features = ["color", "derive", "unicode"] }
dirs = "5.0.1"
dotenvy = "0.15.7"
rayon.workspace = true
sevenz-rust = { version = "0.5.3", optional = true }
shadow-rs = "0.24.1"
tar = { version = "0.4.40", optional = true }
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.39"
tracing-subscriber = "0.3.17"
url = "2.4.1"
wild = "2.2.0"
zip = { version = "0.6.6", optional = true }

[build-dependencies]
shadow-rs = "0.24.1"

[[bin]]
name = "blobary"
path = "src/main.rs"
